# Generated by Django 3.2 on 2021-04-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=250)),
                ('op2', models.CharField(max_length=250)),
                ('op3', models.CharField(max_length=250)),
                ('op4', models.CharField(max_length=250)),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
