# Generated by Django 3.2 on 2021-04-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_hardquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='HardQuestions',
            new_name='EasyQuestion',
        ),
        migrations.RenameModel(
            old_name='EasyQuestions',
            new_name='HardQuestion',
        ),
    ]
